# Generated by Django 5.2.4 on 2025-08-04 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descripcion',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='titulo',
            new_name='title',
        ),
    ]
